# FRBlip quick start

In [1]:
import numpy as np
import pandas as pd

import frblip as frb

import matplotlib.pyplot as plt

## Create a mock of Cosmic Bursts

In [2]:
mock = frb.blips(random_state=42)

get the redshift:

In [3]:
mock.redshift

array([13.7585392 ,  2.12335282,  3.7041686 , ...,  2.61098291,
        5.00125187,  2.90516625])

Luminosity distance:

In [4]:
mock.luminosity_distance

<Quantity [152042.42404822,  17145.10400473,  33500.66419704, ...,
            22031.5637861 ,  47744.42807441,  25056.26482523] Mpc>

Note that frblip uses units from astropy package

possible quantities and methods:

In [5]:
mock.__dict__.keys()

dict_keys(['duration', 'zmin', 'zmax', 'log_L0', 'log_Lstar', 'phistar', 'gamma', 'w_mean', 'w_std', '_spec_idx_dist', 'ra_range', 'dec_range', 'low_frequency', 'high_frequency', 'low_frequency_cal', 'high_frequency_cal', 'igm_model', 'free_electron_bias', 'cosmology', 'host_dist', 'host_source', 'host_model', 'emission_frame', 'start', 'gal_nside', 'gal_method', 'random_state', 'area', '_xmin', '_lumdist', '_cosmology', '_zdist', 'sky_rate', 'size', 'rate', 'params', 'spectral_index', 'redshift', 'luminosity_distance', 'log_luminosity', '_luminosity', 'flux', '_energy_normalization'])

Load a Radio Telescope:

In [6]:
bingo = frb.telescope()

Perform observations on a mock

In [7]:
mock.observe(bingo)

Performing observation for telescope OBS_0...
Computing positions for 106416 sources at site lon=-38.268 deg, lat=-7.041 deg, height=379.000 m.



The results are storage on observations property:

In [8]:
mock.observations

{'OBS_0': <frblip.observation.Observation at 0x7f305fcb1540>}

Computing signal to noise ratio:

In [9]:
mock.signal_to_noise()

<xarray.DataArray (FRB: 106416, OBS_0: 28)>
<COO: shape=(106416, 28), dtype=float64, nnz=16053, fill_value=0.0>
Dimensions without coordinates: FRB, OBS_0

Note that the information is given as a sparse array. To convert it you must pass True to `todense` argument:

In [10]:
mock.signal_to_noise(todense=True)

<xarray.DataArray (FRB: 106416, OBS_0: 28)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
Dimensions without coordinates: FRB, OBS_0

To compute the total value over beams we pass True to the `total` argument

In [11]:
mock.signal_to_noise(total=True, todense=True)

<xarray.DataArray (FRB: 106416)>
array([0., 0., 0., ..., 0., 0., 0.])
Dimensions without coordinates: FRB

The function `triggers` returns if a FRB is observed given minima signal to noise values, default value is range(1, 11):

In [12]:
mock.triggers(todense=True)

<xarray.DataArray (FRB: 106416, OBS_0: 28, SNR: 10)>
array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
...
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]])
Coordinates:
  * SNR      (SNR) int64 1 2 3 4 5 6 7 8 9 10
Dimensions without coordinates: FRB, OBS_0

In [13]:
mock.triggers(todense=True, snr=range(5, 16))

<xarray.DataArray (FRB: 106416, OBS_0: 28, SNR: 11)>
array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
...
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]])
Coordinates:
  * SNR      (SNR) int64 5 6 7 8 9 10 11 12 13 14 15
Dimensions without coordinates: FRB, OBS_0

`counts` method returns the number of observed FRB:

In [14]:
mock.counts()

<xarray.DataArray (OBS_0: 28, SNR: 10)>
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
Coordinates:
  * SNR      (SNR) int64 1 2 3 4 5 6 7 8 9 10
Dimensions without coordinates: OBS_0

In [15]:
mock.counts(total=True)

<xarray.DataArray (SNR: 10)>
array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Coordinates:
  * SNR      (SNR) int64 1 2 3 4 5 6 7 8 9 10

In [16]:
mock.counts(total=True, snr=range(5, 16))

<xarray.DataArray (SNR: 11)>
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Coordinates:
  * SNR      (SNR) int64 5 6 7 8 9 10 11 12 13 14 15

In [19]:
mock.catalog()

{'spectral_index': array([4.81544649]),
 'redshift': array([0.35413267]),
 'luminosity_distance': <Quantity [1942.70696097] Mpc>,
 'log_luminosity': <Dex [42.53975236] dex(erg / s)>,
 'flux': <Quantity [767.40887199] Jy MHz>,
 'right_ascension': <Longitude [300.5745885] deg>,
 'declination': <Latitude [2.04646315] deg>,
 'alt': <Latitude [80.52553114] deg>,
 'az': <Longitude [344.84144275] deg>,
 'obstime': <Time object: scale='utc' format='iso' value=['2023-03-19 10:59:27.435']>,
 'signal_to_noise': <xarray.DataArray (FRB: 1, OBS_0: 28)>
 array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         3.62542606e-296, 4.77398683e-227, 1.71587729e-285,
         1.03440084e-286, 3.33831321e-178, 1.93646591e-118,
         3.14988137e-160, 5.15182127e-185, 5.21095765e-096,
         1.07316150e-046, 2.43429851e-070, 1.26497322e-119,
         6.22013367e-050, 2.3940093